### ISSUE TITLE
Remove HTTPoison as a dependency

### ISSUE THREAD

**Issue by sheharyarn** [slab/safeurl-elixir#2]
There are various HTTP clients in Elixir-land, and devs prefer using one over the other. `SafeURL` should avoid importing an entire HTTP client as a dependency just to make a GET request, and just let the user choose what to call.

After #1, users can simply call something such as:

```elixir
with :ok <- SafeURL.validate(url) do
  HTTPClientOfMyChoice.get(url)
end
```

At the very least, it should use the built-in [`:httpc`](http://erlang.org/doc/man/httpc.html) module or mark `:httpoison` as an optional dependency in `mix.exs` so it's not loaded unless explicitly specified by the user.

**Comment by bhan-slab** [comment]
@sheharyarn do we want to replace the implementation of `get` with an implementation using `httpc` instead of `httpoison`? if so, should we worry about breaking changes since the current definition of `get` has `httpoisin`-specific argument and response types?

**Comment by sheharyarn** [comment]
We should mark `HTTPoison` as an [optional dependency](https://hexdocs.pm/mix/Mix.Tasks.Deps.html#module-options). The `get/4` method should be modified to raise an error "HTTPoison not available" if the library is not available. You can do that by using one of these two approaches:

 - Check that the `:httpoison` application is loaded using [`Application.loaded_applications/0`](https://hexdocs.pm/elixir/1.12/Application.html#loaded_applications/0)
 - The `HTTPoison.get/3` method is available to call using [`Kernel.function_exported?/3`](https://hexdocs.pm/elixir/Kernel.html#function_exported?/3)
